apiVersion: v1
kind: Service
metadata:
  name: redirect-service
  namespace: services
  labels:
    app: redirect-service
spec:
  selector:
    app: redirect-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3003
      name: http
