replicaCount: 1
image:
  repository: ghcr.io/jasvithchand/analytics-service
  tag: "latest"
  pullPolicy: Always
service:
  port: 3004
config:
  port: "3004"
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
