apiVersion: v1
kind: Service
metadata:
  name: shortener-service
  namespace: services
  labels:
    app: shortener-service
spec:
  selector:
    app: shortener-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3002
      name: http
